rule PlugX_Client_Output {
	
	meta:
		description = "Detects Output files generated by earlier versions of PlugX samples"
		author = "https://twitter.com/rsh1r1nov"
		date = "2020-07-01"
		reference = "-"
		score = 70

	strings:
		$t = /(L|l)ocal (T|t)ime: 20[0-9]{2}\/[0-9]{2}\/[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}:[0-9]{0,3}/
		$api1 = "VirtualAllocEx succes" ascii
		$api2 = "CreateRemoteThread succes" ascii
		$api3 = "OpenProcess succes"
		$s1 = "WritePricessMemeory succes" ascii
		$s2 = /errcode is [0-9]{1,2}/
		$s3 = " success!" ascii

	condition:
		$t and ($s1 or (any of ($api*)) or $s2 or $s3) 
}
